# Generated by Django 4.1.5 on 2023-04-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('due', models.IntegerField()),
                ('dose', models.CharField(max_length=15)),
                ('route', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=25)),
            ],
        ),
    ]
