# Generated by Django 4.1.5 on 2023-04-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_taken_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taken',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
